### ISSUE TITLE
Utfordringer under installasjon

### ISSUE THREAD

**Issue by teodorlu** [kodeklubben/oppgaver-wiki#18]
Hei!

Først må jeg kommentere at jeg synes wiki-en har blitt skikkelig bra, @Oisov + andre :+1:

### Om Node og NVM

Jeg har et spørsmål. Forrige gang jeg skrev oppgaver, installerte jeg Node, og brukte global installasjon til å drive oppgavene. Ser at guiden nå anbefaler nvm. Antar det minsker risikoen for feil.

Hva bør jeg gjøre når jeg allerede har Node?

- Bør jeg avinstallere og fjerne referansen til Path for så å la nvm håndtere alt?
- Kan jeg beholde en globalt installert Node og så få denne overskrevet når jeg er i repoer der jeg ønsker prosjekt-anbefalt Node-versjon? (Dette står sikkert i NVM-dokumentasjonen)
- Krever oppgavene en spesifikk Node-versjon?

Spurt av en som ikke sitter med Node hver dag. Ønsker gjerne en bisetning som forklarer :)

Teodor

**Comment by teodorlu** [comment]
Det forvirret meg at `https://github.com/kodeklubben/oppgaver/wiki/Bygge-oppgavesidene-lokalt` refererte til `.nvmrc`, som ikke finnes i oppgave-repoet, men i oppgavebyggeren.

**Comment by teodorlu** [comment]
Kommenterer at NVM legger på cirka et halvt sekund når jeg starter skallet mitt

/rant

**Comment by teodorlu** [comment]
Nå har jeg fått NVM, rett Node-verson opp, og har kjørt `yarn` for å installere avhengigheter (repoet er en gigabyte stort nå).

`yarn start` inne i `./codeclub-vewer` gir meg nå 

```
$ webpack-dev-server -d --progress --inline --hot --host 0.0.0.0
fs.js:667
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open '/home/teodorlu/git/kodeklubben-oppgaver/oppgaver/filtertags/keys.yml'
    at Object.fs.openSync (fs.js:667:18)
    at Object.fs.readFileSync (fs.js:572:33)
    at Function.Utils.getStringFromFile (/home/teodorlu/git/kodeklubben-oppgaver/codeclub-viewer/node_modules/yamljs/lib/Utils.js:284:19)
    at Function.Yaml.parseFile (/home/teodorlu/git/kodeklubben-oppgaver/codeclub-viewer/node_modules/yamljs/lib/Yaml.js:46:21)
    at Function.Yaml.load (/home/teodorlu/git/kodeklubben-oppgaver/codeclub-viewer/node_modules/yamljs/lib/Yaml.js:78:17)
    at lessonPaths (/home/teodorlu/git/kodeklubben-oppgaver/codeclub-viewer/pathlists.js:29:35)
    at getStaticSitePaths (/home/teodorlu/git/kodeklubben-oppgaver/codeclub-viewer/pathlists.js:86:19)
    at Object.<anonymous> (/home/teodorlu/git/kodeklubben-oppgaver/codeclub-viewer/webpack.config.babel.js:71:25)
    at Module._compile (module.js:649:30)
    at loader (/home/teodorlu/git/kodeklubben-oppgaver/codeclub-viewer/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/teodorlu/git/kodeklubben-oppgaver/codeclub-viewer/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at requireConfig (/home/teodorlu/git/kodeklubben-oppgaver/codeclub-viewer/node_modules/webpack/bin/convert-argv.js:97:18)
    at /home/teodorlu/git/kodeklubben-oppgaver/codeclub-viewer/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/teodorlu/git/kodeklubben-oppgaver/codeclub-viewer/node_modules/webpack/bin/convert-argv.js:102:15)
    at Object.<anonymous> (/home/teodorlu/git/kodeklubben-oppgaver/codeclub-viewer/node_modules/webpack-dev-server/bin/webpack-dev-server.js:223:50)
    at Module._compile (module.js:649:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Gjett: ting funker bare dersom `oppgaver`-repoet ligger ved siden av `codeclub-viewer`?

**Comment by teodorlu** [comment]
Ting ser ut til å funke når jeg har `./oppgaver` ved siden av `./codeclub-viewer` :+1:

**Comment by teodorlu** [comment]
Så det finnes jo ting å frustrere seg over med JavaScript når ting blir stort og mange pakker. Håper det er mulig å ta disse kommentarene konstruktivt! For det er slik de er ment.

**Comment by tjesi** [comment]
Vi har oppdatert wikien en del i mellomtiden, og håper at alle problemer skal være besvart nå. Sjekk ut https://github.com/kodeklubben/oppgaver/wiki/Bygge-oppgavesidene-lokalt for en oppdatert og bedre forklaring av installasjonsprosedyren.

For å besvare utfordringene dine (dette står i wikien nå):
* oppgave-repoet og codeclub-viewer må ligge i samme mappe. dette er viktig.
* vi bruker ikke nyeste versjon av Node, men versjon 9.8.0. dette har skapt noen problemer.
* vi henviser nå til `.nvmrc`-filen via url, men skal sørge for at versjonsummer samsvarer med wiki.

Utover dette så er ikke eg så veldig kjent med Node, så evt tekniske spørsmål må nok stilles til noen andre eller sjekkes i dokumentasjonen til Node.
